BlockSigner/five

pages/index.vue

Error case: payment didn't go through
A: Prompt to change payment method or try again in the future
Error case: payment went through but seven returns error
A: prompt to retry request
Error case: everything worked on our side but swisscom/identity.tm fails. How do we handle it? 
A: They received a Stripe email and can contact us through there

[MRG] feat(Error messages): Presents error messages to user

---

.prettierignore
.prettierrc
components/VuetifyLogo.vue
layouts/default.vue
layouts/error.vue
package.json
pages/index.vue
yarn.lock

To format code of everybody according to our rules.

[MRG] build(Prettify): Add prettify config from wave

---

assets/sass/_vars.sass
assets/variables.sass
layouts/default.vue
pages/index.vue

Adds dark section, basic steps, basic button, text helper classes.

[MRG] feat(layout): Add basic layout and content

---

pages/index.vue

Uses new-ish async/wait functions to simplify chaining and error handling of calls in payment method.

[MRG] refactor(Pay method): turns promises into async functions

---

assets/sass/_vars.sass
assets/sass/base.sass
pages/index.vue

Changes font loading display to fallback to be in line with cove.

[MRG] feat(faq): Optimise styling of faq section

---

nuxt.config.js
pages/index.vue

Also remove "coming soon" from the title

[MRG] feat(Stripe payment error msgs): Displays detailed error messages on payment fail

---

assets/sass/_vars.sass
assets/sass/base.sass
assets/variables.sass
nuxt.config.js
pages/index.vue

More polishing of styling. Also removes default assets from build (roboto font, material icons, ...).

[MRG] feat(styling): Update buttons, logo, spacing

---

assets/sass/base.sass
nuxt.config.js
pages/index.vue

Reintroduce material design iconset to display a checkbox.

[MRG] feat(pay): Add form styling

---

assets/sass/base.sass
assets/variables.sass
pages/index.vue

Starts with conditional Vuetify classes for headings and lead text.

[MRG] feat(mobile): Add basic mobile styling

---

pages/index.vue

Make payment work again. Buttons to change status are still there.

[MRG] feat(tos): Add terms of service

---

pages/index.vue

Standardises lateral spacing of container sections.

[MRG] feat(layout): Optimise layout for mobile viewports

---

pages/index.vue

Reduce identity logo and remove dev buttons for form states.

[MRG] feat(price): Increase price per video ident

---

nuxt.config.js
plugins/matomo.js

I propose to PR matomo directly to master branch so we can immediately test if tracking is working on production. The only downside is a few "false positive" visits, but they can be easily taken into account in the future.

[MRG] feat(Matomo): Adds Matomo Tag as plugin

---

pages/index.vue

Not sure about "loszulegen" vs "los zulegen" but my spell checker suggested the new version

[MRG] Spelling fixes

---

netlify.toml

[MRG] Add a redirect for production as well

---

pages/TestTheWest.vue

Adding this so we can test the service "in production" without having to turn on the main page.
The content of `TestTheWest.vue` is a copy of the contents of `Index.vue` revision 46a2cc516507baa6b36be6d9183315a141652536

[MRG] Add normal index page with a weird name for testing

---

pages/index.vue

This adds the real index page content to `index.vue` again. It is a copy of #46. The `testthewest` page isn't removed in this PR just in case someone shares the link to it with one of their friendly faces. I think we should remove it in ~48h or so (soon but not in a hurry).
Patrick used videoident.me to get his eID working again and signed something. So I think we now need more friendly users in order to find the next level of bugs. This means I vote for merging this as soon as we can.
WDYT?

[MRG] Add back the real content

---

pages/index.vue

To make it clearer to users that step 2 and 3 are following.
The rest of the changes is formatting.

[MRG] feat(step 1): Add cardinal number to step 1

---

pages/index.vue

Someone proposed to center the button and I finally did it. Increasing the size helps finding the call to action in the first section.

[MRG] feat(cta): Center 1st button and increase its size

---

nuxt.config.js
package.json
yarn.lock

Also stops loading the roboto font bc we don't use it.

[MRG] build(config): Upgrade core packages and extract css

---

pages/index.vue

According to our GDPR expert's feedback, having a checkbox is not allowed. Be gone!

[MRG] feat(privacy): Remove checkbox for the Skribble privacy policy

---

pages/index.vue

Via @ronioeschger from the board meeting.

[MRG] Fix a typo

---

nuxt.config.js

We'll need to have another look into the FOUC 😐

[MRG] fix(webpack): Remove css extraction as it caused troubles

---

locales/de_CH.js
pages/index.vue

As we think the entire process is not yet ready for english.

[MRG] feat(english): Remove lang switcher, references to english logo

---

README.md
locales/de_CH.js
locales/en_CH.js

Explains how to import locales from Lokalise.
In the process imports the most up to date content.

[MRG] docs(Importing Locales): Quick how to on how to import locales content

---

locales/de_CH.js

Make it even more explicit that video based eIDs won't work after 1. October.

[MRG] update(locales): more explicit messaging for CH

---

locales/de_CH.js

Back to in person identification only 😞

[MRG] Change copy now that the video ident exception in CH has expired

---

components/ThePaymentForm.vue

Fixes https://app.asana.com/0/995964219886332/1198490618451693/f

fix(HTML characters): Allows html characters for a specific string

---

components/ThePaymentForm.vue

The user should see no changes. It's just an improvement to the code. 
Would be good to have a quick test, nevertheless.

refactor(CountryList): Refactors country list code to proper typescript

---

yarn.lock

This PR makes it easy for Dominik to test a single deploy preview with all the dependabot proposed PRs.

build(dependabot): Bundled dependabot PRs from 29 09 2021
